### ISSUE TITLE
Not possible to search for e.g. "words whose plural form is X" because of flattening

### ISSUE THREAD

**Issue by nick8325** [spraakbanken/karp-backend#250]
Suppose we have a resource with words and their inflection tables:

```
{"ortografi": "tå",
 ...,
 {"inflectiontable":
   [{"tag": "singular", "form": "tå"},
    {"tag": "plural", "form": "tår"},
    ...]}},
{"ortografi": "tår",
 ...,
 {"inflectiontable":
   [{"tag": "singular", "form": "tår"},
    {"tag": "plural", "form": "tårar"},
    ...]}}
```

Imagine we want to find all words whose singular form is "tår". We could try running the following query:

```
and(equals|inflectiontable.tag|singular||equals|inflectiontable.form|tår)
```

but this isn't correct: the query returns tår (the correct result), but also tå (which we don't want). This is because it doesn't search for entries having a row `{"tag": "singular", "form": "tår"}` in their `inflectiontable`. Rather it searches for entries where:

* one row in the `inflectiontable` has `"tag": "singular"`
* and one row in `inflectiontable` (maybe a different row) has `"form": "tår"`

so `tå` also matches this query, since it has a row with `"tag": "singular"` and a row with `"form": "tår"` (even though it's two different rows).

Questions:

* Do we want to support searching for things like `{"tag": "singular", "form": "tår"}` (I would guess this could be useful)?
* If so, how should it look like in the query language?

I think we can't execute this kind of query right now because of how the documents are flattened in Elasticsearch, but there's a special [nested type](https://www.elastic.co/guide/en/elasticsearch/reference/current/nested.html#nested-params) and [nested queries](https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-nested-query.html) which might work.

**Comment by majsan** [comment]
It might be possible to index the inflection tables as objects instead of collections:

```
{
  "singular": "tå",
  "plural": "tår",
}
```

But it will only work if each tag is in the table once. Otherwise I think we need to use nested queries.

We probably also want to support finding all entries that have both "tå" and "tår" as word forms. 

Something like `inflectiontable(and(equals|form|tå||equals|tag|singular))` could work for the queries that want to avoid the flattening. "In inflectiontable, do subquery".

**Comment by majsan** [comment]
It is also possible to add new fields to support the searches we want to do either in the Python code or via  https://www.elastic.co/guide/en/elasticsearch/reference/current/ingest.html and then exclude those fields from `_source` so they are never returned to the user. We could combine form and tag into one single field, separated by some delimeter ["tå|singular", "tår|plural"] and then search for an exact match. However, I want to be able to search for (for example) "all entries with word form "tå" where it is *not* the singular form and I'm not sure that's possible.

**Comment by majsan** [comment]
Fixed in b9fd5a4

The new query is `inflectiontable(and(equals|form|tå||equals|tag|singular))` as suggested above. Indices needs to be reindexed before it can work. Uses the type `nested` in ES mapping for all fields with `collection: true` and `type: "object"`.

**Comment by majsan** [comment]
Reopening because:

- Statistics also need to be adapted to nested, there is a nested aggregation
- When querying a field in a single object (`equals|object.field|value`), Karp erroneously generates a nested query. This should only be done for *collections* of objects.

I will fix this ASAP, the broken code is reverted (again).

**Comment by majsan** [comment]
Merged again, hopefully for the last time...
